// Generated by https://quicktype.io

export interface IPosition {
  pueCodigo: number;
  pueCodtpp: number;
  pueNombre: string;
  pueCodgrc: number;
  pueDefinicion: string;
  pueEstado: string;
  pueFechaSupre: string;
  pueEdadMin: number;
  pueEdadMax: number;
  pueEstCivil: string;
  pueSexo: string;
  pueObjetivo: string;
  pueIndicadorCumplimiento: string;
  pueCodncc: number;
  pueRelInternaTodasCias: boolean;
  pueRelInternaTodasUnis: boolean;
  pueRelInternaTodosCdts: boolean;
  puePropertyBagData: string;
  pueEstadoWorkflow: string;
  pueCodigoWorkflow: string;
  pueIngresadoPortal: boolean;
  pueUsuarioGrabacion: string;
  pueFechaGrabacion: string;
  pueUsuarioModificacion: string;
  pueFechaModificacion: string;
  pueWflCeDefAuth: number;
  pueWflCeSolicita: number;
  pueWflCeSujAcc: number;
  pueWflCeAutorizador: number;
}
