export const images = {
  like_gif: require('../LikesImages/like.gif'),
  like_static: require('../LikesImages/ic_like.png'),
  like_static_fill: require('../LikesImages/ic_like_fill.png'),
  love_gif: require('../LikesImages/love.gif'),
  love_static: require('../LikesImages/love2.png'),
  haha_gif: require('../LikesImages/haha.gif'),
  haha_static: require('../LikesImages/haha2.png'),
  wow_gif: require('../LikesImages/wow.gif'),
  wow_static: require('../LikesImages/wow2.png'),
  sad_gif: require('../LikesImages/sad.gif'),
  sad_static: require('../LikesImages/sad2.png'),
  angry_gif: require('../LikesImages/angry.gif'),
  angry_static: require('../LikesImages/angry2.png'),
};
