export enum AppPermissionsEnum {
  inicio = 'inicio',
  ver_dashboard = 'app_ver_dashboard_tecnico',
  aceptar_incidencia = 'app_aceptar_incidencia',
  ver_posibles_soluciones = 'app_ver_posibles_soluciones',
  crear_nueva_solucion = 'app_crear_nueva_solucion',
  aprobar_solicitudes = 'app_aprobar_solicitudes',
}

export const AppPermissions = {
  inicio: 'rol_evowave',
  tecnico: 'MND_APP_TECNICO',
  ver_dashboard: 'MND_APP_VER_DASHBOARD_TECNICO',
  aceptar_incidencia: 'MND_APP_ACEPTAR_INCIDENCIA',
  ver_posibles_soluciones: 'MND_APP_VER_POSIBLES_SOLUCIONES',
  crear_nueva_solucion: 'MND_APP_CREAR_NUEVA_SOLUCION',
  aprobar_solicitudes: 'RolAutorizaciones',
  aprobar_asistencia: 'RolAsistencia',
  aprobar_constancia: 'RolAutorizaConstancias',
  aprobar_constancia_CBA: 'RolAutorizaConstanciasCBA',
  aprobar_constancia_TGU: 'RolAutorizaConstanciasTGU',
  aprobar_acciones_personal: 'RolAutorizadorAcciones',
  aprobar_planillas: 'RolAutorizadorPlanillas',
  aprobar_vacaciones: 'RolVacaciones',
};

export const appPermissionsWeb = [
  'MND_WEB_VER_DASHBOARD_TICKETS',
  'MND_WEB_VER_INCIDENCIA',
  'MND_WEB_CREAR_INCIDENCIA',
  'MND_WEB_EDITAR_INCIDENCIA',
  'MND_WEB_ELIMINAR_INCIDENCIA',
  'MND_WEB_ADMIN_TIPOS_GESTION',
  'MND_WEB_ADMIN_GESTION',
  'MND_WEB_ADMIN_EQUIPOS',
  'MND_WEB_VER_DASHBOARD_RRHH',
  'MND_WEB_VER_BITACORA_RECIBOS',
  'MND_WEB_VER_BITACORA_SOLICITUDES',
  'MND_WEB_APROBAR_SOLICITUDES',
  'MND_WEB_ADMIN_NOTICIAS',
  'MND_WEB_ADMIN_CAT_NOTICIAS',
  'MND_WEB_ADMIN_NOTIFICACIONES',
  'MND_WEB_ADMIN_ACTIVIDADES',
  'MND_WEB_ADMIN_PRODUCTOS',
  'MND_WEB_ADMIN_CANJES',
  'MND_WEB_ADMIN_VOLUNTARIOS',
  'MND_WEB_ADMIN_RECORDATORIOS',
  'MND_WEB_ADMIN_ENCUESTAS',
  'MND_WEB_ADMIN_CLINICAS',
  'MND_WEB_ATENCION_CLINICAS',
  'MND_WEB_ADMIN_CUPONES',
  'MND_WEB_VER_RUTA_SOLICITUDES',
];
