// Generated by https://quicktype.io

import { IEmployeeData } from './IEmployeeData';

export interface IExtraHourDetail {
  request: IExtraHour;
  employeePosition: IEmployeeData;
}

export interface IExtraHour {
  hexCodigo: number;
  hexCodshe: any;
  hexCodemp: number;
  expNombresApellidos: string;
  hexCodempSolicitante: number;
  solicitante: string;
  hexCodppl: number;
  planilla: string;
  pplCodtpl: number;
  tplDescripcion: string;
  hexCodcco: any;
  hexCodthe: any;
  hexEstadoInterpretacion: string;
  hexMensajeInterpretacion: string;
  hexFechaInterpretacion: string;
  hexUsuarioInterpretacion: string;
  hexFechaInicial: string;
  hexFechaFinal: string;
  hexCodtjh: number;
  tjhDescripcion: string;
  hexObservaciones: string;
  hexEstado: string;
  hexFechaCambioEstado: string;
  hexComentarioAnulacion: string;
  hexCodigoWorkflow: string;
  hexEstadoWorkflow: string;
  hexIngresadoPortal: boolean;
  hexPropertyBagData: any;
  hexUsuarioGrabacion: string;
  hexFechaGrabacion: string;
  hexUsuarioModificacion: string;
  hexFechaModificacion: string;
  hexWflCeDefAuth: number;
  hexWflCeSolicita: number;
  hexWflCeSujAcc: number;
  hexWflCeAutorizador: string;
  hexBase: string;
  hexFechaInicialReal: string;
  hexFechaFinalReal: string;
  hexFecha: string;
  expCodigoAlternativo: string;
}
