import { IEmployeeData } from './IEmployeeData';
import { RangeDate } from './IRequestConstancia';

export interface IRequestCupon {
  tipoPermiso: string;
  motivo: string;
  especificaHoras: boolean;
  rangeDate: RangeDate;
  range: string;
  horaDesde: Date;
  horaHasta: Date;
}

// Generated by https://quicktype.io

export interface IPermissionDetail {
  request: IPermissionRequestDetail;
  employeePosition: IEmployeeData;
}

export interface IPermissionRequestDetail {
  slpCodigo: number;
  slpFechaSolicitud: string;
  slpCodempSolicitante: number;
  expNombresApellidos: string;
  slpEstado: string;
  slpFechaCambioEstado: string;
  slpDias: number;
  slpEspecificaHoras: boolean;
  slpHoras: number;
  slpMinutos: number;
  slpModoIngreso: string;
  slpCodtnt: number;
  tntDescripcion: string;
  slpConGoce: boolean;
  slpMotivo: string;
  slpFechaInicio: string;
  slpFechaFin: string;
  slpComentarioAnulacion: string;
  slpPropertyBagData: null;
  slpCodigoWorkflow: string;
  slpEstadoWorkflow: string;
  slpIngresadoPortal: boolean;
  slpUsuarioGrabacion: string;
  slpFechaGrabacion: string;
  slpUsuarioModificacion: string;
  slpFechaModificacion: string;
  slpWflCeDefAuth: number;
  slpWflCeSolicita: number;
  slpWflCeSujAcc: string;
  slpWflCeAutorizador: string;
  expCodigoAlternativo: string;
}
