// Generated by https://quicktype.io

export interface IMessage {
  id: number;
  message: string;
  createdAt: string;
  ticketId: number;
  createdBy: string;
  isSender: boolean;
}

export interface MessageDTO {
  message: string;
  userId: string;
  ticketId: number;
}
